### ISSUE TITLE
connection initiation: negotiation faliure: failureCode = 5

### ISSUE THREAD

**Issue by Moinul78** [kulaginds/rdp-html5#1]
I am testing the project on my local environment, where ssl certificate is absent. The native RDP client works fine. But getting`connection initiation: negotiation faliure: failureCode = 5` this response on the server side. Can you help?

**Comment by kulaginds** [comment]
> HYBRID_REQUIRED_BY_SERVER
> 0x00000005
> 
> The server requires that the client support Enhanced RDP Security (section 5.4) with CredSSP (section 5.4.5.2).
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/1b3920e7-0116-4345-bc45-f2c4ad012761

rdp-html5 is not support enhanced rdp security and credssp. Only rdp over tls.

**Comment by dreygur** [comment]
> I am testing the project on my local environment, where ssl certificate is absent. The native RDP client works fine. But getting`connection initiation: negotiation faliure: failureCode = 5` this response on the server side. Can you help?

Uncheck `Require devices to use network level authentication to connect (Recommended)`
