### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by ne0YT** [kulaginds/rdp-html5#2]
what do I need to run on my linux host to host this app?

**Comment by kulaginds** [comment]
1. Build webserver by `make build`. Should be create file `bin/server`.
2. In console open dir with directory `web`.
3. Run `bin/server` from step 1.
4. Open browser on a page `http://localhost:8080` and pass Windows host, user and password and click `Connect`.

**Comment by ne0YT** [comment]
I ran:
```
/opt/rdp-html5/web# /opt/rdp-html5/bin/server 
2023/08/10 14:57:18 start web-server on :8080
```

it tells me:
404 page not found

on port :8080

**Comment by kulaginds** [comment]
Open parent of `web` directory and try again.

**Comment by ne0YT** [comment]
> Open parent of `web` directory and try again.

I'm pretty impressed by this app rn.
maybe you got some time for a web meeting?

**Comment by ne0YT** [comment]
if you're up to, send me an invitation from jitsi meet, so we can discuss:
https://meet.jit.si/

or tell me iof you're available later
