### ISSUE TITLE
Is it possible to access remote app instead of whole desktop with this client?

### ISSUE THREAD

**Issue by dreygur** [kulaginds/rdp-html5#3]
I am curious to know if it is possible to access remote app instead of whole desktop with this client

**Comment by kulaginds** [comment]
Unfortunately, this client not supported [RAIL](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/485e6f6d-2401-4a9c-9330-46454f0c5aba)  extension.
