### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by LongCX** [kulaginds/rdp-html5#4]
Dear admin,

When i remote my desktop with your library.
Some key on keyboard not working.
Example: When i press key "Numpad1" then keyboard understand "End"
Evidence:
![image](https://github.com/kulaginds/rdp-html5/assets/38092914/512121a0-0f62-479e-b719-734a0d6db847)

Can you checking keymap.js is corrrect ? Thank you !!

**Comment by kulaginds** [comment]
Hi. Can you send description of your environment for reproduce bug?

**Comment by LongCX** [comment]
Dear kulaginds,

Browser to access rdp: Chromium Version 120.0.6099.224
Machine remote: Windows 10 Enterprise LTSC version 1809
Keyboard: Full-size with numpad, layout US.
Note: Only key at numpad not working, other key work fine.
![IMG_2569](https://github.com/kulaginds/rdp-html5/assets/38092914/bf4b1436-ab32-4aff-aebd-ee69bc3a9052)

**Comment by kulaginds** [comment]
Do your NumLock On?

**Comment by kulaginds** [comment]
No answer.
