### ISSUE TITLE
make the window resizable?

### ISSUE THREAD

**Issue by jhjacobs81** [kulaginds/rdp-html5#6]
I've had a hard time setting up Guacamole, and then i came across this nice project :) But i have a hard time configuring it so that the rdp screen is the full with of the browser.  any pointers would be well apreciated :)

**Comment by jhjacobs81** [comment]
i managed to change the size of the canvas, but that leaves the rdp session with this.
![Screenshot_20240606_203829](https://github.com/kulaginds/rdp-html5/assets/5583803/efe95a79-7dae-455c-a04c-335a244e8d44)

**Comment by kulaginds** [comment]
Unfortunately, rdp-html5 project is not supported for dynamic screen resize.
But you can change size of [canvas tag in index.html](https://github.com/kulaginds/rdp-html5/blob/master/web/index.html#L32) and get your size what you need.

**Comment by jhjacobs81** [comment]
thank you for responding. setting the size manually is what i did indeed :) 

Is there a way to make it possible to resize?

**Comment by kulaginds** [comment]
You can resize before connect.
