### ISSUE TITLE
Doesn`t work with RDS servers.

### ISSUE THREAD

**Issue by unknwon00** [kulaginds/rdp-html5#8]
i`ve been able to get this working fine with any RDP server, win10 window server 2019, but it will not work with any Windows Server that had been abled for RDS (remote Desktop Services). it fails to connect with "negotiation failure: failurecode = 2"

its not a user/pass problem.
wfreerdp and sdl-freerdp work fine.

**Comment by kulaginds** [comment]
Hi. rdp-html5 isn't support RDS. Only RDP.

**Comment by unknwon00** [comment]
RDS is just a enterprise RDP.  uses the same protocols.
I saw with freerdp 2.0 there was an error with rds, but i was fixed.  
was hoping there was just some patch that could be applied to correct it too?

**Comment by kulaginds** [comment]
It is toy rdp client only for education.
You can fork it and patch it.

**Comment by unknwon00** [comment]
thanks i would fork it, but i`m new to go lang.  do all my coding in C#.
